## Project
name: BankData
version: "1.0"
config-version: 2
profile: DBT_USER

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  BankData:
    staging:
      +materialized: view
    marts:
      +materialized: table
seeds:
  BankData:
    +persist_docs:
      relation: true
      columns: true
    +post-hook:
      - "{{ apply_seed_constraints(this, model) }}"