DBT_USER:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: NTUZRNP-RS02840
      user: DBT_USER
      role: DBT_DEV_ROLE
      private_key_path: F:\WORK\Creds\rsa_key.p8
      database: BANKING
      schema: dev
      warehouse: compute_wh
    prod:
      type: snowflake
      account: NTUZRNP-RS02840
      user: DBT_USER
      role: DBT_PROD_ROLE
      private_key_path: F:\WORK\Creds\rsa_key.p8
      database: BANKING
      schema: prod
      warehouse: compute_wh