with source as (
        select * from {{ source('FDIC', 'STG') }}
  ),
  renamed as (
      select
          {{ adapter.quote("YEAR") }},
        {{ adapter.quote("CERT") }},
        {{ adapter.quote("BRNUM") }},
        {{ adapter.quote("UNINUMBR") }},
        {{ adapter.quote("NAMEFULL") }},
        {{ adapter.quote("ADDRESBR") }},
        {{ adapter.quote("CITYBR") }},
        {{ adapter.quote("CNTYNAMB") }},
        {{ adapter.quote("STALPBR") }},
        {{ adapter.quote("ZIPBR") }},
        {{ adapter.quote("BRCENM") }},
        {{ adapter.quote("CONSOLD") }},
        {{ adapter.quote("BRSERTYP") }},
        {{ adapter.quote("DEPSUMBR") }},
        {{ adapter.quote("BKMO") }},
        {{ adapter.quote("CBSA_DIV_NAMB") }},
        {{ adapter.quote("CITY2BR") }},
        {{ adapter.quote("CNTRYNAB") }},
        {{ adapter.quote("CNTYNUMB") }},
        {{ adapter.quote("CSABR") }},
        {{ adapter.quote("CSANAMBR") }},
        {{ adapter.quote("DIVISIONB") }},
        {{ adapter.quote("MSABR") }},
        {{ adapter.quote("MSANAMB") }},
        {{ adapter.quote("METROBR") }},
        {{ adapter.quote("MICROBR") }},
        {{ adapter.quote("NAMEBR") }},
        {{ adapter.quote("NECTABR") }},
        {{ adapter.quote("NECNAMB") }},
        {{ adapter.quote("PLACENUM") }},
        {{ adapter.quote("SIMS_ACQUIRED_DATE") }},
        {{ adapter.quote("SIMS_ESTABLISHED_DATE") }},
        {{ adapter.quote("SIMS_LATITUDE") }},
        {{ adapter.quote("SIMS_LONGITUDE") }},
        {{ adapter.quote("SIMS_DESCRIPTION") }},
        {{ adapter.quote("SIMS_PROJECTION") }},
        {{ adapter.quote("STCNTYBR") }},
        {{ adapter.quote("STNAMEBR") }},
        {{ adapter.quote("STNUMBR") }},
        {{ adapter.quote("HCTMULT") }},
        {{ adapter.quote("RSSDHCR") }},
        {{ adapter.quote("NAMEHCR") }},
        {{ adapter.quote("CITYHCR") }},
        {{ adapter.quote("STALPHCR") }},
        {{ adapter.quote("RSSDID") }},
        {{ adapter.quote("UNIT") }},
        {{ adapter.quote("ADDRESS") }},
        {{ adapter.quote("CITY") }},
        {{ adapter.quote("STALP") }},
        {{ adapter.quote("ZIP") }},
        {{ adapter.quote("ASSET") }},
        {{ adapter.quote("BKCLASS") }},
        {{ adapter.quote("CALL") }},
        {{ adapter.quote("CHARTER") }},
        {{ adapter.quote("CHRTAGNN") }},
        {{ adapter.quote("CHRTAGNT") }},
        {{ adapter.quote("CLCODE") }},
        {{ adapter.quote("CNTRYNA") }},
        {{ adapter.quote("DENOVO") }},
        {{ adapter.quote("DEPDOM") }},
        {{ adapter.quote("DEPSUM") }},
        {{ adapter.quote("DOCKET") }},
        {{ adapter.quote("ESCROW") }},
        {{ adapter.quote("FDICDBS") }},
        {{ adapter.quote("FDICNAME") }},
        {{ adapter.quote("FED") }},
        {{ adapter.quote("FEDNAME") }},
        {{ adapter.quote("INSAGNT1") }},
        {{ adapter.quote("INSURED") }},
        {{ adapter.quote("INSBRDD") }},
        {{ adapter.quote("INSBRTS") }},
        {{ adapter.quote("OCCDIST") }},
        {{ adapter.quote("OCCNAME") }},
        {{ adapter.quote("REGAGNT") }},
        {{ adapter.quote("SPECGRP") }},
        {{ adapter.quote("SPECDESC") }},
        {{ adapter.quote("STCNTY") }},
        {{ adapter.quote("STNAME") }},
        {{ adapter.quote("USA") }}

      from source
  )
  select * from renamed
    