{{ config(materialized='table') }}


select
  src.YEAR,
  src.CERTCERTIFICATE_NUMBER,

  -- branch columns
  src.BRANCH_NUMBER,
  src.UNIQUE_BRANCH_NUMBER,
  src.INSTITUTION_NAME,
  src.BRANCH_ADDRESS,
  src.BRANCH_CITY,
  src.BRANCH_COUNTY,
  src.BRANCH_STATE,
  src.BRANCH_ZIP,
  src.BRANCH_REPORTING_TYPE_CODE,
  src.BRANCH_CONSOLIDATION_CODE,
  coalesce(bst.BRANCH_SERVICE_TYPE, concat('Unknown (', src.BRANCH_SERVICE_TYPE_CODE, ')')) as BRANCH_SERVICE_TYPE,
  src.BRANCH_DEPOSIT_AMOUNT,
  src.BRANCH_MAIN_OFFICE_FLAG,
  src.BRANCH_CBSA_DIVISION_NAME,
  src.BRANCH_CITY_FROM_ZIP,
  src.BRANCH_COUNTY_NAME,
  src.BRANCH_COUNTY_NUMBER,
  src.BRANCH_CBSA_NUMBER,
  src.BRANCH_CBSA_NAME,
  src.BRANCH_DIVISION_CODE,
  src.BRANCH_MSA_NUMBER,
  src.BRANCH_MSA_NAME,
  src.BRANCH_DENSE_URBAN_AREA_FLAG,
  src.BRANCH_URBAN_AREA_FLAG,
  src.BRANCH_NAME,
  src.BRANCH_NEW_ENGLAND_PLACE_NUMBER,
  src.BRANCH_NEW_ENGLAND_PLACE_NAME,
  src.BRANCH_FIPS_PLACE_NUMBER,
  src.BRANCH_ACQUIRED_DATE,
  src.BRANCH_ESTABLISHED_DATE,
  src.BRANCH_LATITUDE,
  src.BRANCH_LONGITUDE,
  src.BRANCH_GEOGRAPHY_ACCURACY,
  src.BRANCH_GEOGRAPHY_TYPE,
  src.BRANCH_FIPS_STATE_COUNTY,
  src.BRANCH_STATE_NAME,
  src.BRANCH_FIPS_STATE,

  -- institution columns (excluding amount columns)
  src.INSTITUTION_HOLDING_COMPANY_STATUS,
  src.INSTITUTION_TOP_HOLDING_COMPANY_CODE,
  src.INSTITUTION_TOP_HOLDING_COMPANY_NAME,
  src.INSTITUTION_TOP_HOLDING_COMPANY_CITY,
  src.INSTITUTION_TOP_HOLDING_COMPANY_STATE,
  src.INSTITUTION_FRB_CODE,
  src.INSTITUTION_NO_BRANCHES_FLAG,
  src.INSTITUTION_ADDRESS,
  src.INSTITUTION_CITY,
  src.INSTITUTION_STATE,
  src.INSTITUTION_ZIP,
  coalesce(it.INSTITUTION_TYPE, concat('Unknown (', src.INSTITUTION_TYPE_CODE, ')')) as INSTITUTION_TYPE,
  src.INSTITUTION_CALL_REPORT_TYPE,
  src.INSTITUTION_CHARTER_TYPE,
  src.INSTITUTION_CHARTER_AGENCY,
  src.INSTITUTION_CHARTER_AGENCY_CODE,
  coalesce(ica.INSTITUTION_CATEGORY, concat('Unknown (', src.INSTITUTION_CATEGORY_CODE, ')')) as INSTITUTION_CATEGORY,
  src.INSTITUTION_COUNTRY_NAME,
  src.INSTITUTION_ORIGINAL_CHARTER_FLAG,
  src.INSTITUTION_OTS_DOCKET,
  src.INSTITUTION_FDIC_OFFICE_NUMBER,
  src.INSTITUTION_FDIC_OFFICE_NAME,
  src.INSTITUTION_FED_DISTRICT_CODE,
  src.INSTITUTION_FED_DISTRICT_NAME,
  coalesce(ipi.INSTITUTION_PRIMARY_INSURER, concat('Unknown (', src.INSTITUTION_PRIMARY_INSURER_CODE, ')')) as INSTITUTION_PRIMARY_INSURER,
  coalesce(iit.INSTITUTION_INSURANCE_TYPE, concat('Unknown (', src.INSTITUTION_INSURANCE_TYPE_CODE, ')')) as INSTITUTION_INSURANCE_TYPE,
  src.INSTITUTION_OCC_DISTRICT_CODE,
  src.INSTITUTION_OCC_DISTRICT_NAME,
  src.INSTITUTION_PRIMARY_REGULATOR_CODE,
  coalesce(ipr.INSTITUTION_PRIMARY_REGULATOR, concat('Unknown (', src.INSTITUTION_PRIMARY_REGULATOR_CODE, ')')) as INSTITUTION_PRIMARY_REGULATOR_NAME,
  src.INSTITUTION_SPECIALIZATION_CODE,
  src.INSTITUTION_SPECIALIZATION_DESCRIPTION,
  src.INSTITUTION_STATE_COUNTY_FIPS_CODE,
  src.INSTITUTION_STATE_NAME,
  src.INSTITUTION_US_HEADERQUARTER_FLAG

from {{ ref('summary_of_deposits') }} src
left join {{ ref('BRANCH_SERVICE_TYPE') }} as bst
  on src.BRANCH_SERVICE_TYPE_CODE = bst.BRANCH_SERVICE_TYPE_CODE
left join {{ ref('INSTITUTION_TYPE') }} as it
  on src.INSTITUTION_TYPE_CODE = it.INSTITUTION_TYPE_CODE
left join {{ ref('INSTITUTION_INSURANCE_TYPE') }} as iit
  on src.INSTITUTION_INSURANCE_TYPE_CODE = iit.INSTITUTION_INSURANCE_TYPE_CODE
left join {{ ref('INSITUTION_CATEGORY') }} as ica
  on src.INSTITUTION_CATEGORY_CODE = ica.INSTITUTION_CATEGORY_CODE
left join {{ ref('INSTITUTION_PRIMARY_INSURER') }} as ipi
  on src.INSTITUTION_PRIMARY_INSURER_CODE = ipi.INSTITUTION_PRIMARY_INSURER_CODE
left join {{ ref('INSTITUTION_PRIMARY_REGULATOR') }} as ipr
  on src.INSTITUTION_PRIMARY_REGULATOR_CODE = ipr.INSTITUTION_PRIMARY_REGULATOR_CODE
