{{ config(materialized='table') }}


select
  YEAR,
  CERTCERTIFICATE_NUMBER,
  max(INSTITUTION_NAME) as INSTITUTION_NAME,
  max(INSTITUTION_HOLDING_COMPANY_STATUS) as INSTITUTION_HOLDING_COMPANY_STATUS,
  max(INSTITUTION_TOP_HOLDING_COMPANY_CODE) as INSTITUTION_TOP_HOLDING_COMPANY_CODE,
  max(INSTITUTION_TOP_HOLDING_COMPANY_NAME) as INSTITUTION_TOP_HOLDING_COMPANY_NAME,
  max(INSTITUTION_TOP_HOLDING_COMPANY_CITY) as INSTITUTION_TOP_HOLDING_COMPANY_CITY,
  max(INSTITUTION_TOP_HOLDING_COMPANY_STATE) as INSTITUTION_TOP_HOLDING_COMPANY_STATE,
  max(INSTITUTION_FRB_CODE) as INSTITUTION_FRB_CODE,
  max(INSTITUTION_NO_BRANCHES_FLAG) as INSTITUTION_NO_BRANCHES_FLAG,
  max(INSTITUTION_ADDRESS) as INSTITUTION_ADDRESS,
  max(INSTITUTION_CITY) as INSTITUTION_CITY,
  max(INSTITUTION_STATE) as INSTITUTION_STATE,
  max(INSTITUTION_ZIP) as INSTITUTION_ZIP,
  max(INSTITUTION_ASSET_AMOUNT) as INSTITUTION_ASSET_AMOUNT,
  max(coalesce(IT.INSTITUTION_TYPE, concat('Unknown (', sod.INSTITUTION_TYPE_CODE, ')'))) as INSTITUTION_TYPE,
  max(INSTITUTION_CALL_REPORT_TYPE) as INSTITUTION_CALL_REPORT_TYPE,
  max(INSTITUTION_CHARTER_TYPE) as INSTITUTION_CHARTER_TYPE,
  max(INSTITUTION_CHARTER_AGENCY) as INSTITUTION_CHARTER_AGENCY,
  max(INSTITUTION_CHARTER_AGENCY_CODE) as INSTITUTION_CHARTER_AGENCY_CODE,
  max(coalesce(IC.INSTITUTION_CATEGORY, concat('Unknown (', sod.INSTITUTION_CATEGORY_CODE, ')'))) as INSTITUTION_CATEGORY,
  max(INSTITUTION_COUNTRY_NAME) as INSTITUTION_COUNTRY_NAME,
  max(INSTITUTION_ORIGINAL_CHARTER_FLAG) as INSTITUTION_ORIGINAL_CHARTER_FLAG,
  max(INSTITUTION_DOMESTIC_DEPOSITS_AMOUNT) as INSTITUTION_DOMESTIC_DEPOSITS_AMOUNT,
  max(INSTITUTION_DEPOSITS_AMOUNT) as INSTITUTION_DEPOSITS_AMOUNT,
  max(INSTITUTION_OTS_DOCKET) as INSTITUTION_OTS_DOCKET,
  max(INSTITUTION_ESCROW_AMOUNT) as INSTITUTION_ESCROW_AMOUNT,
  max(INSTITUTION_FDIC_OFFICE_NUMBER) as INSTITUTION_FDIC_OFFICE_NUMBER,
  max(INSTITUTION_FDIC_OFFICE_NAME) as INSTITUTION_FDIC_OFFICE_NAME,
  max(INSTITUTION_FED_DISTRICT_CODE) as INSTITUTION_FED_DISTRICT_CODE,
  max(INSTITUTION_FED_DISTRICT_NAME) as INSTITUTION_FED_DISTRICT_NAME,
  max(coalesce(IPI.INSTITUTION_PRIMARY_INSURER, concat('Unknown (', SOD.INSTITUTION_PRIMARY_INSURER_CODE, ')'))) as INSTITUTION_PRIMARY_INSURER,
  max(coalesce(IIT.INSTITUTION_INSURANCE_TYPE, concat('Unknown (', SOD.INSTITUTION_INSURANCE_TYPE_CODE, ')'))) as INSTITUTION_INSURANCE_TYPE,
  max(INSTITUTION_INSURED_DEPOSITS_US_TERRITORIES_AMOUNT) as INSTITUTION_INSURED_DEPOSITS_US_TERRITORIES_AMOUNT,
  max(INSTITUTION_INSURED_CDS_US_TERRITORIES_AMOUNT) as INSTITUTION_INSURED_CDS_US_TERRITORIES_AMOUNT,
  max(INSTITUTION_OCC_DISTRICT_CODE) as INSTITUTION_OCC_DISTRICT_CODE,
  max(INSTITUTION_OCC_DISTRICT_NAME) as INSTITUTION_OCC_DISTRICT_NAME,
  max(SOD.INSTITUTION_PRIMARY_REGULATOR_CODE) as INSTITUTION_PRIMARY_REGULATOR_CODE,
  max(coalesce(IPR.INSTITUTION_PRIMARY_REGULATOR, concat('Unknown (', SOD.INSTITUTION_PRIMARY_REGULATOR_CODE, ')'))) as INSTITUTION_PRIMARY_REGULATOR_NAME,
  max(INSTITUTION_SPECIALIZATION_CODE) as INSTITUTION_SPECIALIZATION_CODE,
  max(INSTITUTION_SPECIALIZATION_DESCRIPTION) as INSTITUTION_SPECIALIZATION_DESCRIPTION,
  max(INSTITUTION_STATE_COUNTY_FIPS_CODE) as INSTITUTION_STATE_COUNTY_FIPS_CODE,
  max(INSTITUTION_STATE_NAME) as INSTITUTION_STATE_NAME,
  max(INSTITUTION_US_HEADERQUARTER_FLAG) as INSTITUTION_US_HEADERQUARTER_FLAG,
  COUNT(*) as BRANCH_COUNT,
  LISTAGG(DISTINCT BRANCH_STATE, ', ') WITHIN GROUP (ORDER BY BRANCH_STATE) AS STATE_FOOTPRINT

from {{ ref('summary_of_deposits') }} sod
  left join {{ ref('INSTITUTION_TYPE') }} IT on sod.INSTITUTION_TYPE_CODE = IT.INSTITUTION_TYPE_CODE
  left join {{ ref('INSTITUTION_INSURANCE_TYPE') }} IIT on sod.INSTITUTION_INSURANCE_TYPE_CODE = IIT.INSTITUTION_INSURANCE_TYPE_CODE
  left join {{ ref('INSITUTION_CATEGORY') }} IC on sod.INSTITUTION_CATEGORY_CODE = IC.INSTITUTION_CATEGORY_CODE
  left join {{ ref('INSTITUTION_PRIMARY_INSURER') }} IPI on sod.INSTITUTION_PRIMARY_INSURER_CODE = IPI.INSTITUTION_PRIMARY_INSURER_CODE
  left join {{ ref('INSTITUTION_PRIMARY_REGULATOR') }} IPR on sod.INSTITUTION_PRIMARY_REGULATOR_CODE = IPR.INSTITUTION_PRIMARY_REGULATOR_CODE
group by YEAR, CERTCERTIFICATE_NUMBER
