{{ config(
    materialized = 'view'
) }}

select
        TRY_CAST(YEAR AS INT)                       AS YEAR,
        TRY_CAST(CERT AS INT)                       AS CERTCERTIFICATE_NUMBER,
        TRY_CAST(BRNUM AS INT)                      AS BRANCH_NUMBER,
        TRY_CAST(UNINUMBR AS INT)                   AS UNIQUE_BRANCH_NUMBER,
        TRIM(NAMEFULL)                              AS INSTITUTION_NAME,
        TRIM(ADDRESBR)                              AS BRANCH_ADDRESS,
        TRIM(CITYBR)                                AS BRANCH_CITY,
        TRIM(CNTYNAMB)                              AS BRANCH_COUNTY,
        TRIM(STALPBR)                               AS BRANCH_STATE,
        TRY_CAST(ZIPBR AS INT)                      AS BRANCH_ZIP,
        TRIM(BRCENM)                                AS BRANCH_REPORTING_TYPE_CODE,
        TRIM(CONSOLD)                               AS BRANCH_CONSOLIDATION_CODE,
        TRY_CAST(BRSERTYP AS INT)                   AS BRANCH_SERVICE_TYPE_CODE,
        TRY_CAST(DEPSUMBR AS INT) * 1000            AS BRANCH_DEPOSIT_AMOUNT,
        TRY_CAST(BKMO AS INT)                       AS BRANCH_MAIN_OFFICE_FLAG,
        TRIM(CBSA_DIV_NAMB)                         AS BRANCH_CBSA_DIVISION_NAME,
        TRIM(CITY2BR)                               AS BRANCH_CITY_FROM_ZIP,
        TRIM(CNTRYNAB)                              AS BRANCH_COUNTY_NAME,
        TRY_CAST(CNTYNUMB AS INT)                   AS BRANCH_COUNTY_NUMBER,
        TRY_CAST(CSABR AS INT)                      AS BRANCH_CBSA_NUMBER,
        TRIM(CSANAMBR)                              AS BRANCH_CBSA_NAME,
        TRY_CAST(DIVISIONB AS INT)                  AS BRANCH_DIVISION_CODE,
        TRY_CAST(MSABR AS INT)                      AS BRANCH_MSA_NUMBER,
        TRIM(MSANAMB)                               AS BRANCH_MSA_NAME,
        TRY_CAST(METROBR AS INT)                    AS BRANCH_DENSE_URBAN_AREA_FLAG,
        TRY_CAST(MICROBR AS INT)                    AS BRANCH_URBAN_AREA_FLAG,
        TRIM(NAMEBR)                                AS BRANCH_NAME,
        TRY_CAST(NECTABR AS INT)                    AS BRANCH_NEW_ENGLAND_PLACE_NUMBER,
        TRIM(NECNAMB)                               AS BRANCH_NEW_ENGLAND_PLACE_NAME,
        TRY_CAST(PLACENUM AS INT)                   AS BRANCH_FIPS_PLACE_NUMBER,
        TRY_TO_DATE(SIMS_Acquired_Date)             AS BRANCH_ACQUIRED_DATE,
        TRY_TO_DATE(SIMS_Established_Date)          AS BRANCH_ESTABLISHED_DATE,
        TRY_CAST(SIMS_LATITUDE AS DECIMAL(9,6))     AS BRANCH_LATITUDE,
        TRY_CAST(SIMS_LONGITUDE AS DECIMAL(9,6))    AS BRANCH_LONGITUDE,
        TRIM(SIMS_DESCRIPTION)                      AS BRANCH_GEOGRAPHY_ACCURACY,
        TRIM(SIMS_PROJECTION)                       AS BRANCH_GEOGRAPHY_TYPE,
        TRY_CAST(STCNTYBR AS INT)                   AS BRANCH_FIPS_STATE_COUNTY,
        TRY_CAST(STNAMEBR AS INT)                   AS BRANCH_STATE_NAME,
        TRY_CAST(STNUMBR AS INT)                    AS BRANCH_FIPS_STATE,
        TRIM(HCTMULT)                               AS INSTITUTION_HOLDING_COMPANY_STATUS,
        TRIM(RSSDHCR)                               AS INSTITUTION_TOP_HOLDING_COMPANY_CODE,
        TRIM(NAMEHCR)                               AS INSTITUTION_TOP_HOLDING_COMPANY_NAME,
        TRIM(CITYHCR)                               AS INSTITUTION_TOP_HOLDING_COMPANY_CITY,
        TRIM(STALPHCR)                              AS INSTITUTION_TOP_HOLDING_COMPANY_STATE,
        TRY_CAST(RSSDID AS INT)                     AS INSTITUTION_FRB_CODE,
        TRY_CAST(UNIT AS INT)                       AS INSTITUTION_NO_BRANCHES_FLAG,
        TRIM(ADDRESS)                               AS INSTITUTION_ADDRESS,
        TRIM(CITY)                                  AS INSTITUTION_CITY,
        TRIM(STALP)                                 AS INSTITUTION_STATE,
        TRY_CAST(ZIP AS INT)                        AS INSTITUTION_ZIP,
        TRY_CAST(ASSET AS INT) * 1000               AS INSTITUTION_ASSET_AMOUNT,
        TRIM(BKCLASS)                               AS INSTITUTION_TYPE_CODE,
        TRIM(CALL)                                  AS INSTITUTION_CALL_REPORT_TYPE,
        TRIM(CHARTER)                               AS INSTITUTION_CHARTER_TYPE,
        TRIM(CHRTAGNN)                              AS INSTITUTION_CHARTER_AGENCY,
        TRIM(CHRTAGNT)                              AS INSTITUTION_CHARTER_AGENCY_CODE,
        TRY_CAST(CLCODE AS INT)                     AS INSITUTION_CATEGORY_CODE,
        TRIM(CNTRYNA)                               AS INSTITUTION_COUNTRY_NAME,
        TRY_CAST(DENOVO AS INT)                     AS INSTITUTION_ORIGINAL_CHARTER_FLAG,
        TRY_CAST(DEPDOM AS INT)                     AS INSTITUTION_DOMESTIC_DEPOSITS_AMOUNT,
        TRY_CAST(DEPSUM AS INT) * 1000              AS INSTITUTION_DEPOSITS_AMOUNT,
        TRY_CAST(DOCKET AS INT)                     AS INSTITUTION_OTS_DOCKET,
        TRY_CAST(ESCROW AS INT) * 1000              AS INSTITUTION_ESCROW_AMOUNT,
        TRY_CAST(FDICDBS AS INT)                    AS INSTITUTION_FDIC_OFFICE_NUMBER,
        TRIM(FDICNAME)                              AS INSTITUTION_FDIC_OFFICE_NAME,
        TRY_CAST(FED AS INT)                        AS INSTITUTION_FED_DISTRICT_CODE,
        TRIM(FEDNAME)                               AS INSTITUTION_FED_DISTRICT_NAME,
        TRIM(INSAGNT1)                              AS INSTITUTION_PRIMARY_INSURER,
        TRIM(INSURED)                               AS INSTITUTION_INSURANCE_TYPE,
        TRY_CAST(INSBRDD AS INT)                    AS INSTITUTION_INSURED_DEPOSITS_US_TERRITORIES,
        TRY_CAST(INSBRTS AS INT)                    AS INSTITUTION_INSURED_CDS_US_TERRITORIES,
        TRY_CAST(OCCDIST AS INT)                    AS INSTITUTION_OCC_DISTRICT_CODE,
        TRIM(OCCNAME)                               AS INSTITUTION_OCC_DISTRICT_NAME,
        TRIM(REGAGNT)                               AS INSTITUTION_PRIMARY_REGULATOR,
        TRY_CAST(SPECGRP AS INT)                    AS INSTITUTION_SPECIALIZATION_CODE,
        TRIM(SPECDESC)                              AS INSTITUTION_SPECIALIZATION_DESCRIPTION,
        TRY_CAST(STCNTY AS INT)                     AS INSTITUTION_STATE_COUNTY_FIPS_CODE,
        TRIM(STNAME)                                AS INSTITUTION_STATE_NAME,
        TRY_CAST(USA AS INT)                        AS INSTITUTION_US_HEADERQUARTER_FLAG
from {{ source('FDIC', 'STG') }}
